fix

diff --git a/.gitlab/.gitlab-ci.build.tpl.yml b/.gitlab/.gitlab-ci.build.tpl.yml
--- a/.gitlab/.gitlab-ci.build.tpl.yml
+++ b/.gitlab/.gitlab-ci.build.tpl.yml
@@ -77,11 +77,9 @@
           
         echo "Bereinige Registry (Behalte maximal die neuesten $KEEP_VERSIONS Versionen)..."              
         PACKAGES_JSON=$(curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --silent "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages?package_name=galene&sort=desc&order_by=id")
-
         
-
-        if [ -z "$OLD_PACKAGE_IDs" ]; then
-          echo "Registry ist sauber. Keine alten Versionen zum Löschen gefunden."
+        if [ -z "$PACKAGES_JSON" ] || echo "$PACKAGES_JSON" | grep -q "error" || [ "$PACKAGES_JSON" = "[]" ]; then
+          echo "Registry ist noch leer oder neu initialisiert. Keine alten Versionen zum Löschen."
         else
           OLD_PACKAGE_IDs=$(echo "$PACKAGES_JSON" | jq -r ".[${KEEP_VERSIONS}:].id | select(. != null)")
           if [ -z "$OLD_PACKAGE_IDs" ]; then
